name: DeathPenalty
main: com.pandemoneus.deathPenalty.DeathPenalty
version: '1.054'
author: 'Pandemoneus'

commands:
    deathpenalty:
        description: DeathPenalty
        usage: |
               /<command>
    dp:
        description: DeathPenalty
        usage: |
               /<command>